# إعدادات النظام الخلفي لحفظ البيانات إلى فرع Git
backend:
  name: git-gateway  # استخدام Git Gateway للتوثيق
  branch: main       # اسم الفرع الرئيسي

# إعدادات المجلدات للوسائط
media_folder: "static/img"   # المجلد على نظام الملفات لتخزين الوسائط
public_folder: "/img"      # المسار العام للوصول إلى الوسائط

# تعريف المجموعات (collections)
collections:
  - name: pages
    label: Pages
    files:
      - file: "src/pages/index.md"
        label: Home
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown

  - name: blog
    label: Blog
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Post Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
